### ISSUE TITLE
Number of articles and open/close toggle misaligned

### ISSUE THREAD

**Issue by gbcreation** [levito/tt-rss-feedly-theme#101]
As you can see in the screenshot below, the number of articles and the open/close toggle are displayed above the folder names:

![Screenshot_20210623_183406](https://user-images.githubusercontent.com/454315/123134964-9a3c1380-d451-11eb-8ac5-e1170ef0e334.png)

I have this issue with all theme variants provided by tt-rss-feedly-theme.

**Comment by levito** [comment]
Which version of tt-rss do you use (open the preferences and look at the bottom of the screen)? And what's your browser and its version?

**Comment by gbcreation** [comment]
The displayed version is: Tiny Tiny RSS vr10820.4e81233ac (Unsupported)
I don't know why it is indicated "unsupported"?
My Web browser is Firefox 89.0.2 (64-bit) freshly installed. I used v89.0.1 before and had the same issue.

**Comment by levito** [comment]
The versions of tt-rss and the theme don't match. You should either update tt-rss or, if you can't do that, switch back to the theme version 2.7.4.

**Comment by gbcreation** [comment]
Thank you for your answer. I'm going to try version 2.7.4.
