### ISSUE TITLE
Feed badges issue

### ISSUE THREAD

**Issue by maru-sama** [levito/tt-rss-feedly-theme#107]
Hello,

For me the feed badges are still broken after one of the last ttrss updates. I updated to the latest master CSS but this does not fix the issue. They are not styled at all and text-overflow is not working

**Comment by maru-sama** [comment]
Hi,

Small update, this only happens if combined mode is enabled, it works with combined mode disabled.

**Comment by levito** [comment]
Can you please add a screenshot?

**Comment by maru-sama** [comment]
Here you go, should have done this from the beginning...
![Capture](https://user-images.githubusercontent.com/152713/145283326-8399fb24-bdbe-447b-8a5b-dd54e4b1c942.PNG)

**Comment by maru-sama** [comment]
Ok, I think I found it.

Apparently the old files were not cleaned up from the docker image, so although deploying with the new files the old files were still used and it obviously did not work. Sorry for the noise.

**Comment by levito** [comment]
Nevermind 🙂

**Comment by maru-sama** [comment]
I wanted to add and something to my last comment and deleted it instead, let's try this again.

There is still an issue with combined mode. If you open a single feed you the link background is not completely hidden..
![Capture](https://user-images.githubusercontent.com/152713/145290461-fd6b8ba4-9963-48d0-a0aa-031d5945f9f7.PNG)

**Comment by levito** [comment]
Good catch, thanks for the fix!
