### ISSUE TITLE
Increase the font using CSS

### ISSUE THREAD

**Issue by VlaK0r** [levito/tt-rss-feedly-theme#118]
Hello, friends!
Please tell me how to increase the font using CSS?

**Comment by levito** [comment]
Hi @VlaK0r, to change the font sizes, please follow these steps:

1. Enter the preferences
2. Hit the "Customize" button on the "Theme" section
3. Enter a custom style like this:
    ```css
    :root {
      --font-size-post: 20px;
    }
    ```

This will increase the font size for posts and headings, and adjust some spacings so everything is still aligned nicely.

There are some hardcoded font sizes that won't change with this because otherwise the user interface would break.

You can find [more customization options in the readme](https://github.com/levito/tt-rss-feedly-theme#configuration).

**Comment by VlaK0r** [comment]
> Hi @VlaK0r, to change the font sizes, please follow these steps:
> 
>     1. Enter the preferences
> 
>     2. Hit the "Customize" button on the "Theme" section
> 
>     3. Enter a custom style like this:
>        ```css
>        :root {
>          --font-size-post: 20px;
>        }
>        ```
> 
> 
> This will increase the font size for posts and headings, and adjust some spacings so everything is still aligned nicely.
> 
> There are some hardcoded font sizes that won't change with this because otherwise the user interface would break.
> 
> You can find [more customization options in the readme](https://github.com/levito/tt-rss-feedly-theme#configuration).

For example, there is a code.

* These are the default settings for feedly.css */
:root {
  --base-spacing: 30px; /* works best with a value between 30px and 75px */
  --font-size-post: 16px;
  --fonts-ui: "Helvetica Neue", Arial, Helvetica, "Liberation Sans",
    "Nimbus Sans L", FreeSans, sans-serif;
  --fonts-content: var(--fonts-ui);
  --fonts-heading: SansCn;
  --fonts-mono: "Fira Code", Menlo, Monaco, Consolas, "Lucida Console",
    "Liberation Mono", "DejaVu Sans Mono", "Bitstream Vera Sans Mono",
    "Courier New", monospace;
  --reading-width: 45; /* use a unitless `em` value */
  --card-max-column-count: 10;
  --card-min-column-width: 300px;
}

What needs to be changed or added in it to increase the font of the headings or in the left panel?
When I change --font-size-post: 16px; to 30px, the font size only changes in the right window.

**Comment by levito** [comment]
As I mentioned, some font sizes are hardcoded and can't be changed because this would break the layout. You can try something like this to zoom the entire UI:

```css
:root {
    zoom: 1.2;
}
```

Then you can also play with smaller values for `--base-spacing` and/or `--font-size-post` to compensate some unwanted size increases.

**Comment by VlaK0r** [comment]
Thank you very much for your help!
This code (zoom: 1.2;) doesn't change anything for some reason.

But I came out differently. I increased the scale of the page using the browser, but not all pages, only the font. In this case, nothing changes except the font.
It looks wonderful!
Thank you so much for the theme!

**Comment by levito** [comment]
Oh, then you are probably using Firefox, right? `zoom` is non-standard CSS that doesn't work there. Glad that you could make it work for you with browser settings!

**Comment by VlaK0r** [comment]
> Oh, then you are probably using Firefox, right? `zoom` is non-standard CSS that doesn't work there. Glad that you could make it work for you with browser settings!

You can enlarge the font in the right panel by adding -
body.flat.ttrss_index #main {
  font-size: var(--font-size-main,15px);
}
