### ISSUE TITLE
The latest update of TT-RSS breaks the theme.

### ISSUE THREAD

**Issue by VlaK0r** [levito/tt-rss-feedly-theme#127]
![изображение](https://github.com/levito/tt-rss-feedly-theme/assets/77666575/635112a7-fd3f-487a-8750-358ef5eae55a)

**Comment by levito** [comment]
Hey @VlaK0r, could you please point me to what's broken exactly? Looks fine to me at first sight. Also, if can tell, which tt-rss commit broke things? I don't see anything suspicious in the [tt-rss commit history](https://gitlab.tt-rss.org/tt-rss/tt-rss/-/commits/master).

**Comment by VlaK0r** [comment]
> Hey @VlaK0r, could you please point me to what's broken exactly? Looks fine to me at first sight. Also, if can tell, which tt-rss commit broke things? I don't see anything suspicious in the [tt-rss commit history](https://gitlab.tt-rss.org/tt-rss/tt-rss/-/commits/master).

If everything is fine with you, then the problem is on my side.

**Comment by levito** [comment]
I just looked at your screenshot and didn't see anything broken. I also didn't check the most recent tt-rss version yet. So if you could tell me what is broken for you, this would help a lot.

**Comment by VlaK0r** [comment]
> I just looked at your screenshot and didn't see anything broken. I also didn't check the most recent tt-rss version yet. So if you could tell me what is broken for you, this would help a lot.

The sepia color is broken. As you can see in the screenshot, the white color prevails.

**Comment by VlaK0r** [comment]
![изображение](https://github.com/levito/tt-rss-feedly-theme/assets/77666575/a2da9352-6029-4096-86d2-caacdf87fc85)

**Comment by levito** [comment]
The only white bits I can see are the icons/images. This has been the case for ages with this theme. I think in the past, I once experimented with tinting the images as well, but this was making them look strange sometimes.

Also, the dropdowns/menus and inputs have white background. This is intended as well.

Please let me know if I missed something. Otherwise let's close the issue.
