### ISSUE TITLE
Request: Dark feedly

### ISSUE THREAD

**Issue by fhoshino** [levito/tt-rss-feedly-theme#17]
I'd love to have a dark feedly theme for night reading, something like this:
https://userstyles.org/styles/89622/dark-feedly-hauschild-s

**Comment by ScreenDriver** [comment]
+1

**Comment by ScreenDriver** [comment]
+1

**Comment by levito** [comment]
@fhoshino @screendriver you can try one of these forks:
* https://github.com/txtd/tt-rss-feedly-theme-dark
* https://github.com/pleaseremove/tt-rss-feedly-theme-dark
* https://github.com/fluaten/tt-rss-feedly-theme

**Comment by screendriver** [comment]
Thank you for that information.
