### ISSUE TITLE
Styling kind of broken in combined view

### ISSUE THREAD

**Issue by onitreb** [levito/tt-rss-feedly-theme#22]
After going from the last official release version of tt-rss to the master branch, the feedly theme has a little glitch for me. Grabbed latest feedly theme from git.

I have no custom css.

Ideas?

![untitled-1](https://cloud.githubusercontent.com/assets/2154479/9530187/22b869ca-4cb3-11e5-9d72-18f85e32a7b5.jpg)

**Comment by levito** [comment]
Hi @onitreb, Pull the theme again, I fixed it today with @horosgrisa's merge request #20.
