### ISSUE TITLE
single line items not available in widescreen

### ISSUE THREAD

**Issue by benzipperer** [levito/tt-rss-feedly-theme#23]
The feed icon/name and item title take up multiple lines in widescreen mode (see screenshot), differing from the single line they use in screenshots for this project. In not-widescreen mode, the single line name/title seems to work fine.

The problem appears for me in both Chrome and Firefox. How should I help debug this problem?

![screenshot from 2015-10-28 12 21 42](https://cloud.githubusercontent.com/assets/4070964/10795991/8fd7e2d4-7d72-11e5-865d-a9b2d4476f6e.png)

**Comment by levito** [comment]
Hi @benzipperer, this is intended since in widescreen mode the overview area can be very narrow. The headline should have as much space as possible there.

Also, in widescreen mode, the excerpt breaks into multiple lines, otherwide it's on the same line like the icons and actions.
