### ISSUE TITLE
Mark as read when clicking on number of unread articles

### ISSUE THREAD

**Issue by phars** [levito/tt-rss-feedly-theme#24]
Hey Veit, awesome theme! Not really an issue but some kind of a feature request: Feedly marks all articles automatically as read when you click on that little number next to the feed name. You know, the number which indicates the total amount of unread articles within that feed (see the attached image).
Do you plan to implement this feature? Would be nice to mark all articles as read this way :-)
![hn_mark_read](https://cloud.githubusercontent.com/assets/11831994/11755003/a3583c6e-a04f-11e5-9bba-758cb00ad687.jpg)

**Comment by ardichoke** [comment]
I may be mistaken, but I believe this is beyond the scope of a theme to implement. You'd probably have to submit a feature request to the tiny-tiny-rss team (https://tt-rss.org/gitlab/fox/tt-rss/issues).

**Comment by levito** [comment]
Hi @phars, @ardichoke is right, this is not possible with a theme since it's a functionality change, sorry.
