### ISSUE TITLE
If the only content of article is <img> inside of <a>, then article title becomes unclickable

### ISSUE THREAD

**Issue by kuc** [levito/tt-rss-feedly-theme#32]
How to reproduce:

1. Create RSS feed, in which each item contain only that HTML code (below is unescaped version):

```
<a href="http://example.com>
    <img src="https://placeholdit.imgix.net/~text?txtsize=33&txt=350%C3%97150&w=350&h=150">
</a>
```

2. Clicking of article title in expanded view does nothing.

---------------

Adding, for example, `<p>` anywhere in article content solves this. Or setting style `display: block` on that single `<a>` element works, too.

**Comment by sovanyio** [comment]
This problem goes away if the following change is made:
```
.cdmContentInner, .cdmIntermediate {
    margin: 0 0 0;
    padding: 0 33px 10px;
}
```
I'll test locally and PR it if no issues

**Comment by sovanyio** [comment]
Fix PR: https://github.com/levito/tt-rss-feedly-theme/pull/53

**Comment by levito** [comment]
Thanks a lot, I just merged the PR.
