### ISSUE TITLE
broken after 17.1

### ISSUE THREAD

**Issue by fhoshino** [levito/tt-rss-feedly-theme#37]
https://tt-rss.org/gitlab/fox/tt-rss/commit/a86255572a9b9a278a14a1f19dd89e8c80e7db72

**Comment by Takika** [comment]
https://github.com/levito/tt-rss-feedly-theme/pull/36

**Comment by idadzie** [comment]
Change the first line in the feedly.css file from /* supports-version:16.8 */ to /* supports-version:17.10 */

**Comment by levito** [comment]
This is fixed now!
