### ISSUE TITLE
Theme doesn't show up in preferences

### ISSUE THREAD

**Issue by NCols** [levito/tt-rss-feedly-theme#41]
Hello,

I've installed the files on the /themes folder, but the css doesn't show up in the dropdown in the ttrss preferences.

Any idea what I should do?

Thanks!

**Comment by michaelmattig** [comment]
If you installed the latest version of tt-rss, have a look at this issue: https://github.com/levito/tt-rss-feedly-theme/issues/37

**Comment by NCols** [comment]
Great, thanks!

On 8 February 2017 16:36:54 CET, Michael Mattig <notifications@github.com> wrote:
>If you installed the latest version of tt-rss, have a look at this
>issue: https://github.com/levito/tt-rss-feedly-theme/issues/37
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/levito/tt-rss-feedly-theme/issues/41#issuecomment-278362611

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by levito** [comment]
This is fixed now!
