### ISSUE TITLE
Broken theme by 17.4 version bump

### ISSUE THREAD

**Issue by x86dev** [levito/tt-rss-feedly-theme#42]
The TT-RSS commit [467bc4fe03499791bb17a9485b2ea44729600c1b](https://tt-rss.org/fox/tt-rss/commit/467bc4fe03499791bb17a9485b2ea44729600c1b) to bump the version from 17.1 to 17.4 has broken the theme again, unfortunately.

Would be great to get this fixed soon. Thank you!

**Comment by ardichoke** [comment]
The theme itself works just fine as far as I can tell. Just need to bump the version in the feedly.css file. I'll submit a PR for this shortly, but in the meantime you should just be able to make that change in place

**Comment by sebastien4** [comment]
Indeed, it works fine.

**Comment by x86dev** [comment]
Can confirm, works fine here as well, cheers!

**Comment by levito** [comment]
Fixed with #43.
