### ISSUE TITLE
Thumbnail Preview in the Feed?

### ISSUE THREAD

**Issue by MrLordy** [levito/tt-rss-feedly-theme#45]
before it was possible too get his done with some small edits i notices in the forum @ tt-rss. but they do not seem too work anymore.. so is there a way to get this working now? with newest tt-rss and this theme ?

**Comment by juhi24** [comment]
+1. Would be a game changer feature in my opinion. @levito, in the point of view of a theme dev, do you think it'd be simple enough to implement this on individual themes, or should there be some changes in ttrss code? 

The [clean-creader](https://github.com/naeramarth7/clean-greader) theme seems to have [something](https://github.com/naeramarth7/clean-greader#thumbnail-for-main-feed-image--small-main-feed-image-) like this.

**Comment by levito** [comment]
Closing since this would be far too buggy and hacky to implement, at least without some preparation in tt-rss code.
