### ISSUE TITLE
[Enchancement]Option for Dark Version?

### ISSUE THREAD

**Issue by MrsAngelD** [levito/tt-rss-feedly-theme#46]
I love this theme, I was wondering if there is anyone to get a Dark or Nighttime option for it. The layout is fantastic though and I thank you so much for making it 👍

**Comment by levito** [comment]
Hi @MrsAngelD, I'm glad you like the theme! 

There already is a night option: just select *feedly-night.css*.

Cheers!

**Comment by MrsAngelD** [comment]
I don't see an option for feedly-night :( I only have feedly.

**Comment by MrsAngelD** [comment]
Nevermind, for some reason My version didn't have that css file, I recloned the download and now all is well :)
