### ISSUE TITLE
Wrong supports-version in ZIP file

### ISSUE THREAD

**Issue by screendriver** [levito/tt-rss-feedly-theme#47]
https://github.com/levito/tt-rss-feedly-theme/archive/master.zip contains a `feedly.css` that has following first line: `/* supports-version:17.1 */`

It should be `/* supports-version:17.4 */`

**Comment by talklittle** [comment]
Just checked zip, it already has 17.4. Clear your cache?

**Comment by screendriver** [comment]
Hmm strange. You are right. I don't know what was going on my machine :🤔 

Thank you for the response.
