### ISSUE TITLE
Does this work on 16.8?  new install and it's not showing up

### ISSUE THREAD

**Issue by psyciknz** [levito/tt-rss-feedly-theme#48]
I've just installed a new ttrss system on ubuntu.  I've used apt-get rather than install via git (so this means that the base folder of tt-rss is /usr/share/tt-rss/www).

It was also owned by root, so I've done a chown www-data:www-data.  Then followed the instructions for loading the feedly theme:

> /usr/share/tt-rss/www/themes$ la -la
> total 60
> drwxr-xr-x  3 www-data www-data  4096 Aug 15 08:55 .
> drwxr-xr-x 13 www-data www-data  4096 Aug 15 08:31 ..
> -rw-r--r--  1 www-data www-data   111 Aug 26  2016 default.css
> -rw-r--r--  1 www-data www-data     0 Aug 26  2016 .empty
> drwxr-xr-x  5 www-data www-data  4096 Aug 15 08:55 feedly
> -rw-r--r--  1 www-data www-data 38970 Aug 15 08:55 feedly.css
> -rw-r--r--  1 www-data www-data  3899 Aug 26  2016 night.css

So it's appearing here, and seems to have the right permissions.  But doesn't seem to show up.

Any help?

**Comment by Kdecherf** [comment]
You must edit the first line of `feedly.css` to point out your version, please check https://git.tt-rss.org/git/tt-rss/wiki/Themes#themes for more information.

**Comment by psyciknz** [comment]
Thanks, that worked.  I've never had to do that before.  But looks like the theme is from a higher version that the tt-rss site (was my first time using the apt version rather than githubs version

**Comment by levito** [comment]
@psyciknz you might want to use the older commit https://github.com/levito/tt-rss-feedly-theme/tree/07f2973b82e47ea8ee4771e089a608495c89b5c9 in case you encounter any bugs. TT-RSS v17 introduced some incompatible changes.
