### ISSUE TITLE
scrollbar Little error

### ISSUE THREAD

**Issue by remydev** [levito/tt-rss-feedly-theme#49]
Hello

I have a problem with the left view, when all the categories are open, a scrolbar appears, it is possible to draw with the mouse wheel, but not possible to click on scrollbar to change the view.

**Comment by levito** [comment]
Hi @remydev, good catch! I haven't noticed this since my scrollbars are hidden. It should be fixed now - could you please check?

**Comment by remydev** [comment]
yes it's works!

Thanks ;)
