### ISSUE TITLE
Theme Fixes for v 17.12 broken in Firefox

### ISSUE THREAD

**Issue by ardichoke** [levito/tt-rss-feedly-theme#52]
The changes made to make the theme compatible with v 17.12 completely broke the theme in Firefox 57. I ended up having to use another browser to log in and change my theme setting so that it would load and be usable. Not really sure what, specifically, broke it as I'm not much of a CSS guru.

![screen shot 2017-12-18 at 13 18 33-fullpage](https://user-images.githubusercontent.com/112836/34121231-533d22f2-e3f6-11e7-942c-9cfd5abbd848.png)

**Comment by levito** [comment]
Can you please check if you have any custom css applied and if you have pulled the latest theme changes? On OS X running Firefox 57.0.1 everything works as expected.

**Comment by ardichoke** [comment]
Very strange. I pulled the latest changes and do not have any custom CSS applied. Both of the machines that I tested on are running 57.0.1 on Fedora 27, though the underlying OS _shouldn't_ make a difference. I'll have to test again when I'm at home.

**Comment by levito** [comment]
Indeed, this is strange. Could you check which revision of tt-rss you have? Mine is d4c05d0be2c0e865d06b24d334afeeeebadcfd58 - the latest commit as of today.

**Comment by ardichoke** [comment]
It is the same as you listed.

ardichoke@natasha:~/ttrss/tt-rss$ git rev-parse HEAD
d4c05d0be2c0e865d06b24d334afeeeebadcfd58

I have a nightly job that backs up and then updates tt-rss, because I'm lazy and got sick of doing it manually all the time.

**Comment by ardichoke** [comment]
So... is it possible that the fixes for version 17.12 were applied only to the feedly theme and not the feedly-night theme? Because I just tried the base feedly theme and it works, it's only the feedly-night theme that is broken it seems.

**Comment by levito** [comment]
I found the issue and pushed a fix. The color inversion didn't apply anymore because the layout changed in a way that the html element had no height.
