### ISSUE TITLE
Font does not support czech characters

### ISSUE THREAD

**Issue by iguana007** [levito/tt-rss-feedly-theme#54]
Hi,
I am having issues with this theme as Tex Gyre Heros font does not support characters used in Czech language:
ĚŠČŘŽŮĎŤŇ
+
ěščřžůďťň
These letters are rendered with different font and it looks really strange.

**Comment by levito** [comment]
Hi @iguana007, thanks for reporting this. I included the font with all available characters - can you please check if it looks good now? Thanks a lot!

**Comment by iguana007** [comment]
Hi @levito, thank you very much for a quick fix. Sure I will test it, but later, now I am leaving PC for a while and I need to do backup of my current working setup, which I changed to: https://fonts.google.com/specimen/Roboto+Condensed

**Comment by iguana007** [comment]
Hi @levito, seems that your fix has resolved this issue. Thank you very much.
