### ISSUE TITLE
Install problems

### ISSUE THREAD

**Issue by Offerel** [levito/tt-rss-feedly-theme#59]
Hi there. Sure, im new to tt-rss and would like to try it. After installation from Github, tt-rss seems to be on version 18.8. I have copied as advised both css files and the feedly subdir to the themes folder of tt-rss and chowned afterwards all files to www-data (just to be sure). But i couldn't choose the theme from within the settings. Do i miss something or have i done something wrong?

**Comment by kgraefe** [comment]
There is this PR #58 that suggest you'd have to update the compatibility string in both CSS files to `18.8`. (I did not try it myself.)

**Comment by Offerel** [comment]
Ahh. Ok. It seems to work. I had some error messages, but i think they do not belong to the theme. I tweak some settings in parallel and i fear that the messages came from there. Anyway, after changing the version number in the css files, i could choose the theme and after re-login, i can access all areas without a error message. So many thx for that tip.
