### ISSUE TITLE
[Improvement][Bug] Squished text.

### ISSUE THREAD

**Issue by gothrek22** [levito/tt-rss-feedly-theme#61]
Hi,

at the moment the text within the expanded item tab is really squished to the left. It gets worse with bigger aspect ratios or higher resolution.

Would it be possible to change it so it uses more screen real estate?

Here's how it looks at the moment.
![image](https://user-images.githubusercontent.com/1223127/46487658-daba5580-c800-11e8-8875-67e05b585330.png)

**Comment by gothrek22** [comment]
Seems to be an issue here:
https://github.com/levito/tt-rss-feedly-theme/blob/master/feedly.css#L1366

setting it to 90% gives a better look.

**Comment by levito** [comment]
Closing since this is intended and you found a fix for you.

For recent versions, you can either edit https://github.com/levito/tt-rss-feedly-theme/blob/master/src/_content.less#L81 or add this to your custom stylesheet:

```css
.content p { max-width: unset !important; }
```
