### ISSUE TITLE
no date shown for articles

### ISSUE THREAD

**Issue by yafp** [levito/tt-rss-feedly-theme#62]
is it on purpose that the feedly theme shows no timestamp/date for single articles?

**Comment by levito** [comment]
Hi @yafp,

the timestamp/date should always be visible in all the different view modes.

Could you please post a screenshot? Also, which browser are you using, and which version?

**Comment by yafp** [comment]
Hey,
sorry for the delay.

Screenshot is attached.
![20181127_082549](https://user-images.githubusercontent.com/67605/49065388-3102ae00-f21e-11e8-9f92-a1ade22d6c4b.png)

I assume the issue is not a general effect, but related with my setup:
- Firefox (63.0.3) on Linux
- Old tt-rss version (v1.12)

Maybe i can debug it myself ...which css section is responsible for the timestamps/dates?

**Comment by levito** [comment]
Oh, this looks pretty broken. You're right, https://github.com/levito/tt-rss-feedly-theme/releases/tag/v1.1.0 is the theme version you should use.

But I'd suggest to update tt-rss itself and use the theme from master so you get all the fixes in tt-rss and a dark mode (feedly-night) for the theme.
