### ISSUE TITLE
Incompatible against 18.12

### ISSUE THREAD

**Issue by gilbus** [levito/tt-rss-feedly-theme#63]
See [this commit](https://git.tt-rss.org/fox/tt-rss/commit/ac68939d7ecb012fc998f9e6a12bf8b09aadf214)

Manual bumping is possible but a few elements are misaligned.

Thanks for the great theme :+1:

**Comment by psyciknz** [comment]
My container my have just pulled a new version, and the feedlyness has gone....the default theme is quite jarring by comparison.

Love the feedly theme.
