### ISSUE TITLE
Completely broken "thanks" to TTRSS changes

### ISSUE THREAD

**Issue by vinzv** [levito/tt-rss-feedly-theme#65]
As a followup to #63 there are yet again fundamental changes made in TTRSS which break the whole Feedly theme. Could you have a look at it?

**Comment by pgasior** [comment]
I think for now it's better to wait until fox finishes his changes. I have feeling that since last week he made more changes than during whole year. On the other hand README on master branch states that his theme will probably not be updated to support newer versions of tt-rss.

**Comment by seraphyn** [comment]
Hope it will be updated.
30% I read with TTRss via Browser and the rest is via Fiery Feeds on mobile.
Do not ask my how much my eyes hurt, when I need to use the standard theme.
Do we need to open up a bounty?

**Comment by vinzv** [comment]
Count me in - both on the visual pain and an eventual bounty.

**Comment by valvin1** [comment]
Outch ! I've just upgraded TT-RSS and I have the same problem.

I've tested branch v18.12 but unfortunately it doesn't solve the incompatibility.

I really hope that the theme will upgrade it brings a really better feeling to the app. 

@seraphyn let us know if you open a bounty.

**Comment by seraphyn** [comment]
See https://github.com/levito/tt-rss-feedly-theme/issues/66 for more information.

**Comment by x86dev** [comment]
+1 here, just completely broke this wonderful theme. Does anybody know how to temporarily set the classic theme without fiddling with the config file? Can't reach the settings with the mouse anymore ...

**Comment by vinzv** [comment]
Just move the feedly theme folder away or rename feedly.css to anything. TTRSS will revert to default theme then.

**Comment by Gravemind** [comment]
I made a "close enough for me" feedly theme from scratch. Nothing ambitious, I'm not intending to be as refined as levito's theme, but just good enough, and as maintainable as possible:
https://github.com/Gravemind/tt-rss-feedlish-theme

**Comment by seraphyn** [comment]
@Gravemind Why not earn money and Fix the theme?
See the [Bounty](https://github.com/levito/tt-rss-feedly-theme/issues/66)

**Comment by x86dev** [comment]
For me Gravemind's theme "just works fine" (tm), so I'm not that disappointed anymore that TTRSS has broken Levito's (great!) theme ...still, would be nice to get it fixed though.
