### ISSUE TITLE
[Bug] Randomly appearing buttons

### ISSUE THREAD

**Issue by fhoshino** [levito/tt-rss-feedly-theme#67]
With the latest tt-rss and tt-rss-feedly-theme, I got some buttons shown up when enabling showing feed content.
![chrome_2019-01-13_21-12-28](https://user-images.githubusercontent.com/771955/51085708-26718900-1778-11e9-8b3d-30cb665a905a.png)

**Comment by levito** [comment]
This is interesting! Which browser and OS are you using?

**Comment by fhoshino** [comment]
Windows 8.1 x64, Chrome 71 x64

**Comment by pgasior** [comment]
Same thing happening for me. I also noticed that on some feeds header got messed up, and text is too long on some lines. I'm on Firefox 65 on Windows 10.
![firefox_2019-02-05_19-50-26](https://user-images.githubusercontent.com/2581867/52296847-a954c080-297f-11e9-8abe-16e64c3ba857.png)

**Comment by levito** [comment]
Thanks for the screenshot @pgasior, this helped a lot! Should be fixed now.
