### ISSUE TITLE
How can i set this view?

### ISSUE THREAD

**Issue by gnrmarcel** [levito/tt-rss-feedly-theme#68]
Hello, iam new with tiny tiny rss and i find your great feedly theme.
but i can i set this view? 
https://imgur.com/a/HP7dTLj

my articels opens under the feed not like here in the right side.

**Comment by levito** [comment]
Just click "Actions" on the top right, then "Toggle widescreen mode". 

There's also a keyboard shortcut: `a Shift+w`. You can find all shortcuts in the Actions menu.

To hide the feeds holder, click on the left edge of the screen.
