### ISSUE TITLE
resize left pane mouse arrow width too large

### ISSUE THREAD

**Issue by amanalar** [levito/tt-rss-feedly-theme#69]
hey, first thanks for the update.

so the left pane resizing area. the resizing is fine i just cant get the mouse pointer on the left pane scroll bar to drag the bar up or down.

**Comment by levito** [comment]
Thanks a lot for reporting this - I just fixed it.

**Comment by amanalar** [comment]
works great.

on a separate note and ooc, not sure if this is something that needs to be changed in the core or if a theme could change it, but is there way that for example you have a category for lets say 30 feeds and your just reading along using shortcuts and glance at the left pane and the selection is way below the viewable area so youre not which feed your currently on and more importantly to me I can't see how many articles are unread. 

now if i press K to go to the next feed it works but the side pane hasnt moved with me. so i guess my question is if its possible to have that left pane always centered on my current feed without scrolling or dragging the pane bar up/down like i just had you fix. :)


thanks

**Comment by levito** [comment]
Unfortunately this is not possible from within a theme. This might be solvable in the core. Maybe you can open an issue there.

**Comment by levito** [comment]
Oh, I just saw that exactly this issue was fixed in tt-rss core 2 days ago: https://git.tt-rss.org/fox/tt-rss/commit/3827e5b94471653a459e1caeeb909abe2e3597f7

**Comment by amanalar** [comment]
yup that was it, thanks levito.
