### ISSUE TITLE
feedly theme not shown in TT-RSS 18.12 preferences

### ISSUE THREAD

**Issue by lvii** [levito/tt-rss-feedly-theme#72]
Hi

I have running `tt-rss 18.12` in docker with **last version** [linuxserver/tt-rss](https://hub.docker.com/r/linuxserver/tt-rss) :

```
# docker inspect -f '{{ index .Config.Labels "build_version" }}' tt-rss
Linuxserver.io version:- 18.12-ls2 Build-date:- 2019-02-12T14:36:56+00:00
```

I have copied css files to `tt-rss/themes.local/` dir following `README.md` :

```
$ ls -lhF /config/www/tt-rss/themes*
/config/www/tt-rss/themes:
total 12K
-rw-rw-r-- 1 abc abc  328 Nov 30 22:02 compact.css
-rw-rw-r-- 1 abc abc  192 Nov 30 22:02 default.php
-rw-rw-r-- 1 abc abc 4.0K Nov 30 22:02 night.css

/config/www/tt-rss/themes.local:
total 64K
drwxr-xr-x 3 abc abc 4.0K Feb 14 13:31 feedly/
-rw-r--r-- 1 abc abc  60K Feb 14 13:31 feedly.css

$ md5sum /config/www/tt-rss/themes.local/*.css
471016e09edef84ee934f7d179689237  /config/www/tt-rss/themes.local/feedly.css

$ find /config/www/tt-rss/themes.local
/config/www/tt-rss/themes.local
/config/www/tt-rss/themes.local/feedly.css
/config/www/tt-rss/themes.local/feedly
/config/www/tt-rss/themes.local/feedly/fonts
/config/www/tt-rss/themes.local/feedly/fonts/texgyreheroscn-bold-webfont.woff
/config/www/tt-rss/themes.local/feedly/fonts/texgyreheroscn-regular-webfont.ttf
/config/www/tt-rss/themes.local/feedly/fonts/texgyreheroscn-regular-webfont.woff
/config/www/tt-rss/themes.local/feedly/fonts/texgyreheroscn-bolditalic-webfont.woff
/config/www/tt-rss/themes.local/feedly/fonts/texgyreheroscn-italic-webfont.woff
/config/www/tt-rss/themes.local/feedly/fonts/texgyreheroscn-italic-webfont.ttf
/config/www/tt-rss/themes.local/feedly/fonts/texgyreheroscn-bolditalic-webfont.ttf
/config/www/tt-rss/themes.local/feedly/fonts/texgyreheroscn-bold-webfont.ttf
```

There was **no** feedly theme in TT-RSS preferences :

![img](https://i.imgur.com/a8slGWs.png)

**Comment by ltGuillaume** [comment]
Same here...

**Comment by levito** [comment]
Strange... I have no explanation. Have you tried putting the files into `themes` instead of `themes.local`? This would be the old way.

Also, can you ensure that the dockerized ttrss version is 18.12 and not older?

**Comment by ltGuillaume** [comment]
Already tried. Putting the files into `themes/` doesn't work either.
I'm not using the Docker version, but my test installation is quickly set up via Softaculous, footer states `Tiny Tiny RSS v18.12`

**Comment by oblogic7** [comment]
I just ran into the same issue. Have confirmed that it is not a file permission issue.

![image](https://user-images.githubusercontent.com/453840/52979903-604c3580-339d-11e9-8fb8-7f447cc73624.png)

**Comment by ltGuillaume** [comment]
Adding the following line to all css files got the themes to show in the Preferences:
`/* supports-version:18.12 */`

However, this was the result:
![image](https://user-images.githubusercontent.com/4777345/53002066-1d856e80-342c-11e9-8eec-31c6b1fa2ab1.png)

**Comment by lvii** [comment]
Hi @levito 

TT-RSS v18.12 was **no** `lib/flat-ttrss/` dir :

https://git.tt-rss.org/fox/tt-rss/src/4db888c7c281d13d9e2d0a5b9f0fb3aa063e8842/lib

`lib/flat-ttrss/` dir was only in current **master** branch :

https://git.tt-rss.org/fox/tt-rss/src/master/lib/flat-ttrss

`feedly.css` first line `@import url(../lib/flat-ttrss/flat_combined.css);` imported a **not** existing file.

**Comment by levito** [comment]
Sorry for the inconvenience, ttrss versioning is kind of broken. There was a short period of time when everything was changing rapidly and the version was already at 18.12. If you are not seeing this theme in the preferences, you are probably using this state of ttrss code. Please update from ttrss master then. Since ttrss uses rolling release, that's the official way to go anyway.
