### ISSUE TITLE
Installation instructions seems out-of-date

### ISSUE THREAD

**Issue by kgraefe** [levito/tt-rss-feedly-theme#73]
I guess `cp feedly.css feedly-night.css [TT-RSS_Home]/themes.local` should be `cp feedly-*.css [TT-RSS_Home]/themes.local`?

`feedly-night.css` does not exist anymore and you added a lot more CSS files (=themes?).

**Comment by Rundfunk** [comment]
Just experienced the same as my Docker buildscript stopped working. Maybe the screenshots should be updated as well to get an overview of the new themes.

(BTW: great job on this theme, I :heart: it!)

**Comment by Rundfunk** [comment]
> I guess `cp feedly.css feedly-night.css [TT-RSS_Home]/themes.local` should be `cp feedly-*.css [TT-RSS_Home]/themes.local`?
> 
> `feedly-night.css` does not exist anymore and you added a lot more CSS files (=themes?).

@kgraefe: with this copy command, `feedly.css` won't be copied as it does not contain a dash. Use the command below to copy all files:

`cp feedly*.css [TT-RSS_Home]/themes.local`

**Comment by levito** [comment]
Thanks guys, I updated the readme
