### ISSUE TITLE
Score icon functionality

### ISSUE THREAD

**Issue by fgtham** [levito/tt-rss-feedly-theme#77]
I really like this theme, thank you for writing it :smile:

I noticed that the score icon behaviour differs in two ways from that of the default theme:

- the icon is only visible if you hover over an article headline,
- clicking on the icon has no effect. The default theme opens a dialog box where you can modify the score instead.

Would it be possible to get the same score icon behaviour as in the default theme?

**Comment by levito** [comment]
Hi @fgtham,

I would like to keep the theme as clean as possible, that's why the icons are only shown on hover.

I tried the score icon in all 4 display modes and could not reproduce your problem: Clicking the icon always showed the dialog box to modify the score.

Which browser (and version) are you using? Do you use TT-RSS from git? Which version and/or commit do you have?

**Comment by fgtham** [comment]
> I would like to keep the theme as clean as possible, that's why the icons 
> are only shown on hover.

No problem :)

> I tried the score icon in all 4 display modes and could not reproduce your 
> problem: Clicking the icon always showed the dialog box to modify the score.
>
>
> Which browser (and version) are you using?

It does not work with firefox 68 on android and 69 on linux. I just tried 
with vivaldi 2.8, where it works as expected. I can test other browsers on 
monday.

> Do you use TT-RSS from git?

Yes, I'm using tt-rss f1df2c505. The feedly-theme commit is 8b2c7f9.

**Comment by levito** [comment]
Good catch, Firefox didn't like the styles. It's fixed now. Thanks for reporting!

**Comment by fgtham** [comment]
Wow, that was fast. Works fine now. Thanks!

**Comment by levito** [comment]
Hey @fgtham, I just wanted to let you know that I recently made the score icon stay visible once a score was set. And there are a lot of other improvements on top. Please feel free to give it a try and let me know how you like it!

**Comment by fgtham** [comment]
Hi @levito thanks for letting me know. I stopped using tt-rss in the meantime and cannot test :frowning_face:
