### ISSUE TITLE
Undefined values after recent tt-rss update

### ISSUE THREAD

**Issue by MEGAMENE** [levito/tt-rss-feedly-theme#78]
Hi, I started having this undefined values after an tt-rss update last week, I think they changed something to do with counters based on the commit history but I'm not sure.
This doesn't happen with the default tt-rss theme.
Is anyone having this problem too?
![Annotation 2020-02-23 220300](https://user-images.githubusercontent.com/7219991/75121056-87aca100-5688-11ea-83e3-badfa38166c7.png)

**Comment by levito** [comment]
Hi @MEGAMENE, thanks for reporting this! It should be fixed now.
