### ISSUE TITLE
Missing article count

### ISSUE THREAD

**Issue by fgtham** [levito/tt-rss-feedly-theme#79]
Commit 313a508 removes the article count:

![missing_count](https://user-images.githubusercontent.com/1180356/75136610-8067b080-56e5-11ea-8cb3-8658f4cbbb4b.png)

Reverting to e1070c6 fixes the issue:

![count_present](https://user-images.githubusercontent.com/1180356/75136643-983f3480-56e5-11ea-8af4-05b94f95e39e.png)

I see this in both firefox and vivaldi (chromium-based).

**Comment by levito** [comment]
Hi @fgtham, this is a breaking change in Tiny Tiny RSS. This theme is supposed to be run on the most current code. Please update Tiny Tiny RSS and the article count will be visible again. If you can't update, you can stick with the previous commit.

**Comment by fgtham** [comment]
Ah, I wasn't aware of that. Works great after upgrading tt-rss, thank you!

**Comment by levito** [comment]
You're welcome! I'm glad that it works now!
