### ISSUE TITLE
[Bug] Theme feedly-sepia_auto does not work

### ISSUE THREAD

**Issue by ZNspace** [levito/tt-rss-feedly-theme#81]
It looks like the extension name is duplicated when feedly-sepia.css is introduced
![image](https://user-images.githubusercontent.com/20868262/76053682-fbb04880-5fa8-11ea-9dce-7fcffb7083cd.png)

**Comment by levito** [comment]
Oops! Thanks for pointing this out @ZNspace, it's fixed now.
