### ISSUE TITLE
which theme used in Readme demo image?

### ISSUE THREAD

**Issue by derust** [levito/tt-rss-feedly-theme#86]
After install, there are `feedly-compact` `feedly-cozy` etc , which one used in readme demo?

I like the one-article-one-line  style,
but whichever  I try, I can't get the style show in readme demo
![](https://raw.githubusercontent.com/derust/wiki/master/20201223185048.png)
![](https://raw.githubusercontent.com/derust/wiki/master/20201223184807.png)

**Comment by levito** [comment]
Hi @derust, this is another setting: Scroll a bit down in the preferences and disable "combined mode". This enables the split view with articles list and details separated.

You can also put the list and details side by side by enabling "widescreen mode" via the burger menu.

Also, checkout "keyboard shortcuts help" to learn how to quickly switch layouts.

Cheers and Merry Christmas!

**Comment by derust** [comment]
thanks @levito
