### ISSUE TITLE
Missing Icon Fonts

### ISSUE THREAD

**Issue by rusitschka** [levito/tt-rss-feedly-theme#90]
Following your installation instructions I'm getting 404s for the material fonts:

https://ttrss.domain/lib/iconfont/MaterialIcons-Regular.woff2
https://ttrss.domain/lib/iconfont/MaterialIcons-Regular.woff
https://ttrss.domain/lib/iconfont/MaterialIcons-Regular.ttf

refrenced from

https://ttrss.domain/themes.local/feedly-cozy.css

Should I put them to /lib/iconfont/ manually?

**Comment by levito** [comment]
Which version of Tiny Tiny RSS do you have?

If you are on a version from Mid February or earlier, please use https://github.com/levito/tt-rss-feedly-theme/releases/tag/v2.6.1.

The current master is meant for the latest Tiny Tiny RSS, which is going through heavy changes right now.

**Comment by rusitschka** [comment]
I'm on the current master of ttrss. Also checked the git repo and /lib/iconfont folder does not exist: https://git.tt-rss.org/fox/tt-rss/src/branch/master/lib

**Comment by rusitschka** [comment]
Found the issue. For some reason my browser still cached an old version of feedly theme CSS. It's working now. Thanks for help! Closing :-)
