### ISSUE TITLE
Infinite spinners

### ISSUE THREAD

**Issue by schmidi** [levito/tt-rss-feedly-theme#91]
With the latest tt rss updates from master branch, the spinners and loaders have been replaced.
In the feedly theme this causes infinitely spinning icons.

![Screenshot_20210317_212652](https://user-images.githubusercontent.com/411354/111534040-cf0c4080-8767-11eb-9893-d11d0babad72.png)

**Comment by levito** [comment]
Can you please pull again? Should be fixed now.

**Comment by schmidi** [comment]
Just pulled and the theme is no longer broken! Thanks for the fast fix!
