### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by evgen-20** [levito/tt-rss-feedly-theme#93]
Hi!
How can I fix the problem with icon fonts? 
My version tt-rss - v21.04-0f61675 (https://git.tt-rss.org/fox/ttrss-docker-compose/src/branch/static-dockerhub/docker-compose.yml)
Errors:
downloadable font: download failed (font-family: "Material Icons" style:normal weight:400 stretch:100 src index:3): status=2147746065 source: https://site.me/tt-rss/lib/iconfont/MaterialIcons-Regular.woff
downloadable font: download failed (font-family: "Material Icons" style:normal weight:400 stretch:100 src index:3): status=2147746065 source: https://site.me/tt-rss/lib/iconfont/MaterialIcons-Regular.woff2
downloadable font: download failed (font-family: "Material Icons" style:normal weight:400 stretch:100 src index:3): status=2147746065 source: https://site.me/tt-rss/lib/iconfont/MaterialIcons-Regular.ttf

![изображение](https://user-images.githubusercontent.com/47032403/115615344-85c78780-a2f7-11eb-870d-38e648e2e6e8.png)

**Comment by levito** [comment]
Hi @evgen-20, this issue was already fixed (#90). Do you use the [most recent release](https://github.com/levito/tt-rss-feedly-theme/releases/latest) of this theme? If so, please try clearing your browser cache.

Cheers!

**Comment by evgen-20** [comment]
Now I restarted the docker-compose with a tt-rss. Opened the container app. 
`docker exec -it  docker_app_1 sh`
And deleted everything in the directory /var/www/html/tt-rss/themes.local.
```
/var/www/html/tt-rss/themes.local # rm -rf *
/var/www/html/tt-rss/themes.local # wget https://github.com/levito/tt-rss-feedly-theme/blob/master/feedly.css
```
Then I downloaded only one style - feedly.css. And opened tt-rss into chrome in incognito.
![изображение](https://user-images.githubusercontent.com/47032403/115958865-fa760e00-a511-11eb-8a8c-246a63ae892b.png)

But all these actions did not help me = (

**Comment by levito** [comment]
Do you see the icons when using the default theme?

**Comment by evgen-20** [comment]
Yes
![изображение](https://user-images.githubusercontent.com/47032403/115960560-c7844800-a51a-11eb-8f9e-73e2e5946d8c.png)

**Comment by levito** [comment]
Very strange, you're getting the old path from before the fix for #90. Like you're still using an old version of this theme. Maybe there is an old version in `/var/www/html/tt-rss/themes`?

**Comment by levito** [comment]
Hey @evgen-20, could you already solve your issue?

**Comment by evgen-20** [comment]
Indeed, somewhere there was an old css. I installed clean tt-rss and it worked.

**Comment by levito** [comment]
Cool, I'm glad we could solve this!
