### ISSUE TITLE
Article scrolling hotkeys not working

### ISSUE THREAD

**Issue by lrsksr** [levito/tt-rss-feedly-theme#95]
### The standard hotkeys for scrolling inside an article do not work:
`Shift+Down` Scroll down
`Shift+Up` Scroll up
`N` Scroll down page
`Shift+PgDn` Scroll down page
`P` Scroll up page
`Shift+PgUp` Scroll up page

### Cause
The element that gets the scroll event is selected by ID `#content-insert` in [L443 and L446 of Article.js](https://git.tt-rss.org/fox/tt-rss/src/branch/master/js/Article.js#L443).
In the original theme, the element is scrollable with the article header scrolling out of view when you use the hotkeys or the mouse wheel.
The feedly theme keeps the header while scrolling and only the sub-sub-element `#content` is scrollable, not the parent. The wrong element gets the scroll event and thus nothing happens.

Thanks for looking into it!

**Comment by levito** [comment]
Hi @lrsksr, good catch, thanks for reporting this! Could you please check if it works now?

**Comment by lrsksr** [comment]
Wow, that was fast.
I can confirm that it works now, thank you very much!
